// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | RealisationsSlice
  | MethodologieSlice
  | ExpertiseSlice
  | RichTextSlice
  | AtelierSlice
  | TemoignagesSlice
  | ProblemesSlice
  | PourquoiLuminaSlice
  | CtaFinalSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Footer Social Links*
 */
export interface SettingsDocumentDataFooterSocialLinksItem {
  /**
   * Icon field in *Settings → Footer Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_social_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "email" | "linkedin" | "twitter" | "instagram" | "website"
  >;

  /**
   * Link field in *Settings → Footer Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Navigation CTA field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >; /**
   * Footer Primary Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_primary_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  footer_primary_text: prismic.RichTextField;

  /**
   * Footer Navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_navigation: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Footer Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_social_links[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSocialLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *Atelier → Default → Primary → Principles*
 */
export interface AtelierSliceDefaultPrimaryItemsItem {
  /**
   * Title field in *Atelier → Default → Primary → Principles*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *Atelier → Default → Primary → Principles*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.items[].body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *Atelier → Default → Primary*
 */
export interface AtelierSliceDefaultPrimary {
  /**
   * Eyebrow field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Studio · Nîmes
   * - **API ID Path**: atelier.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Intro field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.intro
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  intro: prismic.RichTextField;

  /**
   * Manifesto field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.manifesto
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  manifesto: prismic.RichTextField;

  /**
   * Principles field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<AtelierSliceDefaultPrimaryItemsItem>>;

  /**
   * Closing Text field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.closing_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  closing_text: prismic.RichTextField;

  /**
   * CTA Link field in *Atelier → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: atelier.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Atelier Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AtelierSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AtelierSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Atelier*
 */
type AtelierSliceVariation = AtelierSliceDefault;

/**
 * Atelier Shared Slice
 *
 * - **API ID**: `atelier`
 * - **Description**: About page for Lumina Consulting
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AtelierSlice = prismic.SharedSlice<
  "atelier",
  AtelierSliceVariation
>;

/**
 * Primary content in *CtaFinal → Default → Primary*
 */
export interface CtaFinalSliceDefaultPrimary {
  /**
   * Heading field in *CtaFinal → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_final.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Text field in *CtaFinal → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_final.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * CTA Link field in *CtaFinal → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta_final.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for CtaFinal Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaFinalSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaFinalSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CtaFinal*
 */
type CtaFinalSliceVariation = CtaFinalSliceDefault;

/**
 * CtaFinal Shared Slice
 *
 * - **API ID**: `cta_final`
 * - **Description**: Full-width closing CTA block
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaFinalSlice = prismic.SharedSlice<
  "cta_final",
  CtaFinalSliceVariation
>;

/**
 * Item in *Expertise → Default → Primary → Items*
 */
export interface ExpertiseSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *Expertise → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "pen_tool"
    | "terminal"
    | "rocket"
    | "bar_chart"
    | "users"
    | "lightbulb"
    | "target"
    | "gem"
    | "zap"
    | "shield_check"
    | "handshake"
  >;

  /**
   * Title field in *Expertise → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Expertise → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Expertise → Default → Primary*
 */
export interface ExpertiseSliceDefaultPrimary {
  /**
   * Label field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ExpertiseSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Expertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExpertiseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Expertise*
 */
type ExpertiseSliceVariation = ExpertiseSliceDefault;

/**
 * Expertise Shared Slice
 *
 * - **API ID**: `expertise`
 * - **Description**: Expertise
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseSlice = prismic.SharedSlice<
  "expertise",
  ExpertiseSliceVariation
>;

/**
 * Item in *Methodologie → Default → Primary → Items*
 */
export interface MethodologieSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *Methodologie → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "users"
    | "pen_tool"
    | "gem"
    | "rocket"
    | "lightbulb"
    | "target"
    | "message_circle"
  >;

  /**
   * Title field in *Methodologie → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Methodologie → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Methodologie → Default → Primary*
 */
export interface MethodologieSliceDefaultPrimary {
  /**
   * Label field in *Methodologie → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Methodologie → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *Methodologie → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<MethodologieSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Methodologie Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MethodologieSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MethodologieSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Methodologie*
 */
type MethodologieSliceVariation = MethodologieSliceDefault;

/**
 * Methodologie Shared Slice
 *
 * - **API ID**: `methodologie`
 * - **Description**: Methodologie
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MethodologieSlice = prismic.SharedSlice<
  "methodologie",
  MethodologieSliceVariation
>;

/**
 * Item in *PourquoiLumina → Default → Primary → Items*
 */
export interface PourquoiLuminaSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *PourquoiLumina → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: pourquoi_lumina.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "user_check" | "activity" | "flask_conical" | "trending_up"
  >;

  /**
   * Title field in *PourquoiLumina → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pourquoi_lumina.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *PourquoiLumina → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pourquoi_lumina.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *PourquoiLumina → Default → Primary*
 */
export interface PourquoiLuminaSliceDefaultPrimary {
  /**
   * Label field in *PourquoiLumina → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Pourquoi Lumina
   * - **API ID Path**: pourquoi_lumina.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *PourquoiLumina → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pourquoi_lumina.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *PourquoiLumina → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pourquoi_lumina.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<PourquoiLuminaSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for PourquoiLumina Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PourquoiLuminaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PourquoiLuminaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PourquoiLumina*
 */
type PourquoiLuminaSliceVariation = PourquoiLuminaSliceDefault;

/**
 * PourquoiLumina Shared Slice
 *
 * - **API ID**: `pourquoi_lumina`
 * - **Description**: Why Lumina — asymmetric 2-col with sticky heading
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PourquoiLuminaSlice = prismic.SharedSlice<
  "pourquoi_lumina",
  PourquoiLuminaSliceVariation
>;

/**
 * Item in *Problemes → Default → Primary → Items*
 */
export interface ProblemesSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *Problemes → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: problemes.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"eye_off" | "clock" | "shield_off">;

  /**
   * Title field in *Problemes → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: problemes.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Problemes → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: problemes.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Problemes → Default → Primary*
 */
export interface ProblemesSliceDefaultPrimary {
  /**
   * Label field in *Problemes → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Le constat
   * - **API ID Path**: problemes.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Problemes → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: problemes.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *Problemes → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: problemes.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ProblemesSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Problemes Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProblemesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProblemesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Problemes*
 */
type ProblemesSliceVariation = ProblemesSliceDefault;

/**
 * Problemes Shared Slice
 *
 * - **API ID**: `problemes`
 * - **Description**: Pain points section — vertical list layout
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProblemesSlice = prismic.SharedSlice<
  "problemes",
  ProblemesSliceVariation
>;

/**
 * Item in *Realisations → Default → Primary → Items*
 */
export interface RealisationsSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Title field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Badge (optional) field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Refonte en cours, En cours…
   * - **API ID Path**: realisations.default.primary.items[].badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Link field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Realisations → Default → Primary*
 */
export interface RealisationsSliceDefaultPrimary {
  /**
   * Label field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<RealisationsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Realisations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RealisationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RealisationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Realisations*
 */
type RealisationsSliceVariation = RealisationsSliceDefault;

/**
 * Realisations Shared Slice
 *
 * - **API ID**: `realisations`
 * - **Description**: Realisations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RealisationsSlice = prismic.SharedSlice<
  "realisations",
  RealisationsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Badge field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Title First Line field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title_first_line
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_first_line: prismic.RichTextField;

  /**
   * Title Second Line field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title_second_line
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_second_line: prismic.RichTextField;

  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Solid" | "Outlined"
    >
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Item in *Temoignages → Default → Primary → Testimonials*
 */
export interface TemoignagesSliceDefaultPrimaryItemsItem {
  /**
   * Quote field in *Temoignages → Default → Primary → Testimonials*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: temoignages.default.primary.items[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Name field in *Temoignages → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Christiane & Stéphane
   * - **API ID Path**: temoignages.default.primary.items[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Context (optional) field in *Temoignages → Default → Primary → Testimonials*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Mariage · Site événementiel
   * - **API ID Path**: temoignages.default.primary.items[].context
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  context: prismic.KeyTextField;

  /**
   * Rating (1–5) field in *Temoignages → Default → Primary → Testimonials*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5
   * - **API ID Path**: temoignages.default.primary.items[].rating
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  rating: prismic.NumberField;
}

/**
 * Primary content in *Temoignages → Default → Primary*
 */
export interface TemoignagesSliceDefaultPrimary {
  /**
   * Label field in *Temoignages → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ce qu'ils en disent
   * - **API ID Path**: temoignages.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Testimonials field in *Temoignages → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: temoignages.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<TemoignagesSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Temoignages Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TemoignagesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TemoignagesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Temoignages*
 */
type TemoignagesSliceVariation = TemoignagesSliceDefault;

/**
 * Temoignages Shared Slice
 *
 * - **API ID**: `temoignages`
 * - **Description**: Testimonials section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TemoignagesSlice = prismic.SharedSlice<
  "temoignages",
  TemoignagesSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataFooterSocialLinksItem,
      AllDocumentTypes,
      AtelierSlice,
      AtelierSliceDefaultPrimaryItemsItem,
      AtelierSliceDefaultPrimary,
      AtelierSliceVariation,
      AtelierSliceDefault,
      CtaFinalSlice,
      CtaFinalSliceDefaultPrimary,
      CtaFinalSliceVariation,
      CtaFinalSliceDefault,
      ExpertiseSlice,
      ExpertiseSliceDefaultPrimaryItemsItem,
      ExpertiseSliceDefaultPrimary,
      ExpertiseSliceVariation,
      ExpertiseSliceDefault,
      MethodologieSlice,
      MethodologieSliceDefaultPrimaryItemsItem,
      MethodologieSliceDefaultPrimary,
      MethodologieSliceVariation,
      MethodologieSliceDefault,
      PourquoiLuminaSlice,
      PourquoiLuminaSliceDefaultPrimaryItemsItem,
      PourquoiLuminaSliceDefaultPrimary,
      PourquoiLuminaSliceVariation,
      PourquoiLuminaSliceDefault,
      ProblemesSlice,
      ProblemesSliceDefaultPrimaryItemsItem,
      ProblemesSliceDefaultPrimary,
      ProblemesSliceVariation,
      ProblemesSliceDefault,
      RealisationsSlice,
      RealisationsSliceDefaultPrimaryItemsItem,
      RealisationsSliceDefaultPrimary,
      RealisationsSliceVariation,
      RealisationsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      TemoignagesSlice,
      TemoignagesSliceDefaultPrimaryItemsItem,
      TemoignagesSliceDefaultPrimary,
      TemoignagesSliceVariation,
      TemoignagesSliceDefault,
    };
  }
}
