// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PageDocumentDataSlicesSlice =
  | RealisationsSlice
  | MethodologieSlice
  | ExpertiseSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Footer Social Links*
 */
export interface SettingsDocumentDataFooterSocialLinksItem {
  /**
   * Icon field in *Settings → Footer Social Links*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_social_links[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "email" | "linkedin" | "twitter" | "instagram" | "website"
  >;

  /**
   * Link field in *Settings → Footer Social Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_social_links[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Site Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.site_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  site_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.meta_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Navigation CTA field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation_cta
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  navigation_cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  > /**
   * Footer Primary Text field in *Settings*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_primary_text
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */;
  footer_primary_text: prismic.RichTextField;

  /**
   * Footer Navigation field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_navigation
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  footer_navigation: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * Footer Social Links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_social_links[]
   * - **Tab**: Footer
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  footer_social_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterSocialLinksItem>
  >;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes = PageDocument | SettingsDocument;

/**
 * Item in *Expertise → Default → Primary → Items*
 */
export interface ExpertiseSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *Expertise → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "pen_tool"
    | "terminal"
    | "rocket"
    | "bar_chart"
    | "users"
    | "lightbulb"
    | "target"
  >;

  /**
   * Title field in *Expertise → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Expertise → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Expertise → Default → Primary*
 */
export interface ExpertiseSliceDefaultPrimary {
  /**
   * Label field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Items field in *Expertise → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: expertise.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<ExpertiseSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Expertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ExpertiseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Expertise*
 */
type ExpertiseSliceVariation = ExpertiseSliceDefault;

/**
 * Expertise Shared Slice
 *
 * - **API ID**: `expertise`
 * - **Description**: Expertise
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ExpertiseSlice = prismic.SharedSlice<
  "expertise",
  ExpertiseSliceVariation
>;

/**
 * Item in *Methodologie → Default → Primary → Items*
 */
export interface MethodologieSliceDefaultPrimaryItemsItem {
  /**
   * Icon field in *Methodologie → Default → Primary → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    | "users"
    | "pen_tool"
    | "gem"
    | "rocket"
    | "lightbulb"
    | "target"
    | "message_circle"
  >;

  /**
   * Title field in *Methodologie → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Methodologie → Default → Primary → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *Methodologie → Default → Primary*
 */
export interface MethodologieSliceDefaultPrimary {
  /**
   * Label field in *Methodologie → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Methodologie → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Items field in *Methodologie → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: methodologie.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<MethodologieSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Methodologie Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MethodologieSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MethodologieSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Methodologie*
 */
type MethodologieSliceVariation = MethodologieSliceDefault;

/**
 * Methodologie Shared Slice
 *
 * - **API ID**: `methodologie`
 * - **Description**: Methodologie
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MethodologieSlice = prismic.SharedSlice<
  "methodologie",
  MethodologieSliceVariation
>;

/**
 * Item in *Realisations → Default → Primary → Items*
 */
export interface RealisationsSliceDefaultPrimaryItemsItem {
  /**
   * Image field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Title field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Link field in *Realisations → Default → Primary → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Realisations → Default → Primary*
 */
export interface RealisationsSliceDefaultPrimary {
  /**
   * Label field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Heading field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * CTA Link field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Items field in *Realisations → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: realisations.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<RealisationsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Realisations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RealisationsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RealisationsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Realisations*
 */
type RealisationsSliceVariation = RealisationsSliceDefault;

/**
 * Realisations Shared Slice
 *
 * - **API ID**: `realisations`
 * - **Description**: Realisations
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RealisationsSlice = prismic.SharedSlice<
  "realisations",
  RealisationsSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Badge field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.badge
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  badge: prismic.KeyTextField;

  /**
   * Title First Line field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title_first_line
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_first_line: prismic.RichTextField;

  /**
   * Title Second Line field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.title_second_line
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_second_line: prismic.RichTextField;

  /**
   * Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;

  /**
   * CTA field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.cta
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Solid" | "Outlined"
    >
  >;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataFooterSocialLinksItem,
      AllDocumentTypes,
      ExpertiseSlice,
      ExpertiseSliceDefaultPrimaryItemsItem,
      ExpertiseSliceDefaultPrimary,
      ExpertiseSliceVariation,
      ExpertiseSliceDefault,
      MethodologieSlice,
      MethodologieSliceDefaultPrimaryItemsItem,
      MethodologieSliceDefaultPrimary,
      MethodologieSliceVariation,
      MethodologieSliceDefault,
      RealisationsSlice,
      RealisationsSliceDefaultPrimaryItemsItem,
      RealisationsSliceDefaultPrimary,
      RealisationsSliceVariation,
      RealisationsSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
    };
  }
}
