// Code generated by Slice Machine. DO NOT EDIT.

import { defineSliceZoneComponents } from "@prismicio/vue";
import { defineAsyncComponent } from "vue";

export const components = defineSliceZoneComponents({
  a_propos: defineAsyncComponent(() => import("./APropos/index.vue")),
  temoignages: defineAsyncComponent(() => import("./Temoignages/index.vue")),
  expertise: defineAsyncComponent(() => import("./Expertise/index.vue")),
  methodologie: defineAsyncComponent(() => import("./Methodologie/index.vue")),
  realisations: defineAsyncComponent(() => import("./Realisations/index.vue")),
  rich_text: defineAsyncComponent(() => import("./Hero/index.vue")),
  problemes: defineAsyncComponent(() => import("./Problemes/index.vue")),
  pourquoi_lumina: defineAsyncComponent(() => import("./PourquoiLumina/index.vue")),
  cta_final: defineAsyncComponent(() => import("./CtaFinal/index.vue")),
});
